const labels = {
    'takeselfie': "Take a selfie",
    'heywelcome': 'Welcome! ',
    'plsinformbelow': 'Let\'s begin the verification process',
    'panwelcome': 'Great start! ',
    'paninformbelow': 'Keep your PAN card handy',
    'aadharwelcome': 'You are almost there!',
    'aadharinformbelow': 'Complete Aadhaar verification using Digilocker',

    'instruction': 'Instructions',
    'instructionsubheader': 'Please read the following instructions carefully for capturing a selfie',
    'selfieprvw': "Your selfie capture preview",
    'selfieprvwsuntxt': 'Ensure the image is clear.',
    'selfiecpt': 'Selfie Capture',
    'selfiefocused': 'Enough light should be there in the room and selfie should be clear and focused.',
    'selfieeye': 'Please ensure your eyes are open during the selfie capture',
    'selfieblur': 'The picture/photo should not be blurred',
    'selfiespecs': 'Please remove your sunglasses before starting your KYC.',
    'selfiemultiface': 'Avoid multiple faces on camera and look straight in to the camera.',
    'selfieflashlight': 'Avoid backlight flash.',
    'selfieflash': 'Avoid partial face capture.',
    'pleasenote': 'Please Note:',
    'pleasenotetext': 'Poor image/video quality may result in errors.',


    'per_info': 'Personal Information',
    'pftfb': 'Kindly confirm your mobile number and email address. Then proceed to complete the form and provide a selfie for verification.',
    'pn_vrfy': 'PAN Verification',
    'cpt_frnt_back_pan': 'Capture or Upload your PAN card',
    'adh_vrfy': 'Aadhaar Verification',
    'cpt_adhr': 'Give access to your DigiLocker account to finish verification',

    'aadharvrfy': "Your Aadhaar details will be used for Aadhaar verification",
    'panphoto': 'A photograph of your PAN card will be collected to perform PAN verification.',
    'livelocn': 'Your live Location will be Captured in the Verification process.',
    'agreeall': 'I agree with all the above mentioned points and hereby, confirm my consent. ',
    'proceed': 'Proceed',

    'your_name': 'Full Name ',
    'your_name_placeholder': 'Enter full name ',
    'phone_number': 'Phone Number',
    'phone_number_placeholder': 'Enter your phone number ',
    'OTP_mobile_placeholder': 'Enter 4 digits otp ',
    'OTP_email_placeholder': 'Enter 6 digits otp ',
    'email_id': 'Personal email ID',
    'email_id_placeholder': 'Enter email id ',
    'gender': "Gender",
    "dob": "Date of Birth",
    'current_addres': 'Current Address (Optional)',
    'addres_1': 'Address Line 1',
    'addres_2': 'Address Line 2',
    'enter_address_placeholder': 'Enter your address',
    'city_state': 'City and State',
    'country': 'Country',
    'state': 'State',
    'uan_number': 'UAN Number',
    'uan_number_placeholder': 'Enter your UAN number ',
    'close': 'Close',
    'gndrplaceholder': 'Select a gender',
    'stateplaceholder': 'Select a state',
    'dntUAT': "Don't know your UAN?",
    'clkhre': "Click here",


    'dntgoback': 'Do not go back in any step of the KYC process.',
    'panoption': 'Select one of your option',
    'capturepan': 'Capture/ Upload PAN',
    'uploadpan': 'Upload e-PAN',
    'instructpanheading': 'Instructions to capture PAN',
    'ensuretext': 'Ensure the Text on the ID card is clear.',
    'clrimg': 'The image should be clear.',
    'framefit': 'The card should fit in the frame.',
    'noblur': 'The image should not be blurred.',
    'nopotrait': 'The image should not be captured in portrait.',
    'noflash': 'Do not use flash while capturing the ID.',
    'getsatrted': 'Get Started',

    'cropimg': 'Crop Image',
    'capture_pan_frnt': 'Capture front side of the PAN card',
    'insideframe': 'Fit the card inside the frame',

    'underreview': 'The verification process has been successfully submitted. It is under Auditor review.',
    'agreetoall': 'I agree to the all ',

    'emp': 'Employee ',
    'cpt_frnt_back_id': 'Capture front and back of your National ID card',
    'try_again': "Try Again",
    'submission_fail': "Submission Failed",
    'verification': 'Verification',
    'letstart': 'Let’s Start',
    'pholderdob': 'Please select your dob',
    'pholderpan': 'Please enter your PAN number',

    'madewithidflow': 'Made with idflow',
    'frontpan': 'Front side of the PAN card',
    'rotate': 'Rotate',
    'retake': 'Retake',
    'cntnue': 'Continue',
    'img_clr': 'Ensure the image is clear.',
    'veri_fail': 'Verification Failed',
    'modal_text': 'We are not able to recognize your PAN card, please try again.',
    'submit': 'Submit',
    'plsuploadepan': 'Please upload e-PAN PDF and PDF password.',
    'pwd': 'Password',
    'upload': 'Upload',
    'epan': 'e-PAN',
    'pan': 'PAN',
    'Preview': 'Preview',
    'edit': 'Edit',
    'name': 'Name',
    'father_name': 'Father Name',
    'father_name_placeholder': "Enter your father name",
    'pan_id': 'PAN',
    'please_wait': "Please wait",
    'adhar_page_text': 'Proceed with Digilocker for Aadhaar verfication',
    'aaddetails': 'Aadhaar Details',
    'uid': 'UID',
    'address': 'Address',
    'thnku': 'Thank you!',
    'tc': 'terms and conditions ',
    'pp': 'Privacy policy ',
    'nd': ' and ',
    'vrfy_otp': 'Verify OTP',
    'usrcnst': 'User Consent',
    'proceedtodigi': 'Proceed to Digilocker',
    'reload': 'Reload'
}

export default labels